(define (domain circuits)
	(:requirements :typing)
	(:types	moveable - object
		switch - moveable
		wire - moveable
		lamp - moveable
		battery - object
		location)
	(:predicates (connected ?y - location)
		     (connected-wire ?y - location)
		     (connected-switch ?y - location)
		     (connected-lamp ?y - location)
		     (at ?x - object ?y - location)
		     (holding ?x - moveable)
		     (handempty))
	(:action pick-up
		 :parameters (?x - moveable ?y - location)
		 :precondition (and (at ?x ?y)
		 	       	    (handempty))
		 :effect (and (holding ?x)
		 	      (not (at ?x ?y))
			      (not (connected ?y))
			      (not (connected-wire ?y))
			      (not (connected-switch ?y))
			      (not (connected-lamp ?y))
			      (not (handempty))))
	(:action put-down-wire
		 :parameters (?x - wire ?y - location)
		 :precondition (and (holding ?x)
		 	       	    (not (connected ?y )))
		 :effect (and (not (holding ?x))
		 	      (handempty)
			      (connected ?y)
			      (connected-wire ?y)
			      (at ?x ?y)))
	(:action put-down-switch
		 :parameters (?x - switch ?y - location)
		 :precondition (and (holding ?x)
		 	       	    (not (connected ?y )))
		 :effect (and (not (holding ?x))
		 	      (handempty)
			      (connected ?y)
			      (connected-switch ?y)
			      (at ?x ?y)))
	(:action put-down-lamp
		 :parameters (?x - lamp ?y - location)
		 :precondition (and (holding ?x)
		 	       	    (not (connected ?y )))
		 :effect (and (not (holding ?x))
		 	      (handempty)
			      (connected ?y)
			      (connected-lamp ?y)
			      (at ?x ?y))))